[package]
name = "openfairdb"
version = "0.4.4"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>", "slowtec GmbH <post@slowtec.de>"]
keywords = ["geo", "fair", "sustainability"]
homepage = "https://github.com/slowtec/openfairdb"
repository = "https://github.com/slowtec/openfairdb"
license = "AGPL-3.0-or-later"
edition = "2018"

[patch.crates-io]
geocoding = { git = "https://github.com/georust/geocoding" }
tantivy = { git = "https://github.com/tantivy-search/tantivy" }

[dependencies]
chrono = "*"
# clap 3 is supposed to introduce breaking changes
clap = "2"
csv = "*"
diesel = { version = "*", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "*", features = ["sqlite"]  }
dotenv = "*"
env_logger = "*"
failure = "*"
fast_chemail = { version = "*", optional = true }
geocoding = "*"
itertools = "*"
lazy_static = "*"
log = "*"
num-derive = "*"
num-traits = "*"
openssl = { version = "*", features = ["vendored"] }
passwords = "*"
pwhash = "*"
quick-error = "*"
quoted_printable = { version = "*", optional = true }
regex = "*"
rocket = "*"
rocket_contrib = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
slug = "*"
tantivy = "0.9.0-dev"
tempdir = "*"
toml = "*"
url = "*"
uuid = { version = "*", features = ["v4"] }

[dev-dependencies]
rand = "*"

[features]
default = ["email"]
email = ["fast_chemail", "quoted_printable"]
