[package]
name = "openfairdb"
version = "0.3.8"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>"]
license = "AGPL-3.0-or-later"

[dependencies]
# clap 3 is supposed to introduce breaking changes
clap = "2"
log = "*"
env_logger = "*"
uuid = { version = "*", features = ["v4"] }
url = "*"
quick-error = "*"
rocket = "*"
rocket_codegen = "*"
rocket_contrib = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
chrono = "*"
lazy_static = "*"
regex = "*"
pwhash = "*"
fast_chemail = "*"
quoted_printable = "*"
toml = "*"
dotenv = "*"
diesel = { version = "*", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "*", features = ["sqlite"]  }
csv = "*"

[features]
default = ["email"]
email = []
